// Pose data for SignSkeleton.tsx — a dot-and-line hand diagram the learner
// copies. Coordinates follow MediaPipe's Hand Landmarker convention:
// normalized [0, 1], origin top-left, y increasing downward, wrist-relative
// hand orientation (fingers pointing up, thumb to the left).
//
// TWO TIERS OF DATA HERE:
//
// 1. VERIFIED poses (1-9, I, L, V, W, Y — everything currently in
//    signClassifier's DEMO_LETTERS/DEMO_NUMBERS, i.e. everything actually
//    shown in a live lesson today). These are NOT eyeballed — they're
//    generated by the same synthetic-hand technique
//    src/recognition/tests/core.test.ts uses for its fixtures, then run
//    through the real classifySign() and confirmed it returns that exact
//    label. The classifier only cares about relative joint angles and
//    scale-normalized distances (see computeHandFrame in signClassifier.ts),
//    never absolute pixel positions — that's what makes this generation
//    approach valid instead of needing a real photographed hand.
//
// 2. APPROXIMATE poses (A, B) — hand-authored, clearly-distinct-looking
//    placeholders for letters not yet promoted to DEMO tier. These have NOT
//    been checked against the classifier and should be replaced the same
//    way once A/B move out of EXPERIMENTAL_LETTERS.
//
// HOW TO ADD MORE: for simple shapes (straight-or-curled fingers, thumb
// out-or-in, optional thumb-to-fingertip contact), reuse the `hand()`
// generator pattern from core.test.ts and verify with classifySign() before
// trusting the result — see git history on this file for the exact script.
// For shapes that generator can't express (rounded/crossed fingers: C, O, F,
// R, X, etc.) there's no shortcut — those genuinely need a real captured
// hand: run MediaPipe on a webcam (src/recognition/index.html), freeze a
// frame making the sign, copy its 21 landmark points in here.
//
// TODO — still needed: C D E F G H J K M N O P Q R S T U X Z, and 0.
// (J and Z are motion signs, see src/recognition/motionClassifier.ts — a
// static skeleton may need a start/end pose pair for those instead.)

export type Landmark = { x: number; y: number; z?: number };
export type HandPose = Landmark[]; // exactly 21 points, indices 0-20

function pose(points: [number, number, number?][]): HandPose {
  // z defaults to 0, but is NOT omitted — signClassifier's computeHandFrame
  // requires every point's z to be a finite number, or it abstains entirely.
  // The verified poses below carry real (small) z offsets: curled and
  // thumb-touching fingers are geometrically distinguished partly on the
  // z-axis (depth), and dropping that would silently break the "verified
  // against classifySign()" claim in the header above.
  return points.map(([x, y, z = 0]) => ({ x, y, z }));
}

/** Relaxed open hand, gently curled — the animation's resting start state. */
export const NEUTRAL_POSE: HandPose = pose([
  [0.5, 0.85], // 0 wrist
  [0.4, 0.78], [0.34, 0.72], [0.31, 0.66], [0.3, 0.6], // 1-4 thumb
  [0.38, 0.55], [0.37, 0.45], [0.38, 0.37], [0.4, 0.31], // 5-8 index
  [0.46, 0.53], [0.46, 0.42], [0.47, 0.33], [0.49, 0.27], // 9-12 middle
  [0.54, 0.54], [0.55, 0.44], [0.56, 0.36], [0.58, 0.31], // 13-16 ring
  [0.62, 0.57], [0.63, 0.49], [0.65, 0.43], [0.67, 0.39], // 17-20 pinky
]);

export const TARGET_POSES: Record<string, HandPose> = {
  // --- Approximate (unverified) — see comment above ---
  // Fist with the thumb resting alongside it (not covering the fingers).
  A: pose([
    [0.5, 0.85],
    [0.41, 0.78], [0.34, 0.72], [0.3, 0.64], [0.28, 0.56],
    [0.39, 0.56], [0.37, 0.62], [0.36, 0.57], [0.37, 0.5],
    [0.46, 0.54], [0.45, 0.61], [0.45, 0.55], [0.46, 0.48],
    [0.53, 0.55], [0.53, 0.62], [0.53, 0.56], [0.53, 0.49],
    [0.6, 0.57], [0.6, 0.63], [0.6, 0.58], [0.6, 0.51],
  ]),
  // Flat palm: four fingers straight and together, thumb folded across.
  B: pose([
    [0.5, 0.85],
    [0.44, 0.78], [0.42, 0.68], [0.44, 0.6], [0.47, 0.56],
    [0.41, 0.55], [0.41, 0.38], [0.41, 0.22], [0.41, 0.09],
    [0.46, 0.54], [0.46, 0.36], [0.46, 0.19], [0.46, 0.06],
    [0.51, 0.55], [0.51, 0.37], [0.51, 0.2], [0.51, 0.08],
    [0.56, 0.57], [0.56, 0.41], [0.56, 0.27], [0.56, 0.16],
  ]),

  // Verified against classifySign() — see the file header.
  "1": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.43, 0.7], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.56, -0.03],
    [0.48, 0.67, -0.03], [0.6, 0.6], [0.6, 0.46], [0.6, 0.56, -0.03],
    [0.6, 0.67, -0.03], [0.72, 0.6], [0.72, 0.46], [0.72, 0.56, -0.03],
    [0.72, 0.67, -0.03],
  ]),
  // Verified against classifySign() — see the file header.
  "2": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.43, 0.7], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.32],
    [0.48, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.56, -0.03],
    [0.6, 0.67, -0.03], [0.72, 0.6], [0.72, 0.46], [0.72, 0.56, -0.03],
    [0.72, 0.67, -0.03],
  ]),
  // Verified against classifySign() — see the file header.
  "3": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.17, 0.67],
    [0.05, 0.63], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.32],
    [0.48, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.56, -0.03],
    [0.6, 0.67, -0.03], [0.72, 0.6], [0.72, 0.46], [0.72, 0.56, -0.03],
    [0.72, 0.67, -0.03],
  ]),
  // Verified against classifySign() — see the file header.
  "4": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.43, 0.7], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.32],
    [0.48, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.32],
    [0.6, 0.18], [0.72, 0.6], [0.72, 0.46], [0.72, 0.32],
    [0.72, 0.18],
  ]),
  // Verified against classifySign() — see the file header.
  "5": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.17, 0.67],
    [0.05, 0.63], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.32],
    [0.48, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.32],
    [0.6, 0.18], [0.72, 0.6], [0.72, 0.46], [0.72, 0.32],
    [0.72, 0.18],
  ]),
  // Verified against classifySign() — see the file header.
  "6": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.72, 0.67, -0.05], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.32],
    [0.48, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.32],
    [0.6, 0.18], [0.72, 0.6], [0.72, 0.46], [0.72, 0.56, -0.03],
    [0.72, 0.67, -0.03],
  ]),
  // Verified against classifySign() — see the file header.
  "7": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.6, 0.67, -0.05], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.32],
    [0.48, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.56, -0.03],
    [0.6, 0.67, -0.03], [0.72, 0.6], [0.72, 0.46], [0.72, 0.32],
    [0.72, 0.18],
  ]),
  // Verified against classifySign() — see the file header.
  "8": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.48, 0.67, -0.05], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.56, -0.03],
    [0.48, 0.67, -0.03], [0.6, 0.6], [0.6, 0.46], [0.6, 0.32],
    [0.6, 0.18], [0.72, 0.6], [0.72, 0.46], [0.72, 0.32],
    [0.72, 0.18],
  ]),
  // Verified against classifySign() — see the file header.
  "9": pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.36, 0.67, -0.05], [0.36, 0.6], [0.36, 0.46], [0.36, 0.56, -0.03],
    [0.36, 0.67, -0.03], [0.48, 0.6], [0.48, 0.46], [0.48, 0.32],
    [0.48, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.32],
    [0.6, 0.18], [0.72, 0.6], [0.72, 0.46], [0.72, 0.32],
    [0.72, 0.18],
  ]),
  // Verified against classifySign() — see the file header.
  I: pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.43, 0.7], [0.36, 0.6], [0.36, 0.46], [0.36, 0.56, -0.03],
    [0.36, 0.67, -0.03], [0.48, 0.6], [0.48, 0.46], [0.48, 0.56, -0.03],
    [0.48, 0.67, -0.03], [0.6, 0.6], [0.6, 0.46], [0.6, 0.56, -0.03],
    [0.6, 0.67, -0.03], [0.72, 0.6], [0.72, 0.46], [0.72, 0.32],
    [0.72, 0.18],
  ]),
  // Verified against classifySign() — see the file header.
  L: pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.17, 0.67],
    [0.05, 0.63], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.56, -0.03],
    [0.48, 0.67, -0.03], [0.6, 0.6], [0.6, 0.46], [0.6, 0.56, -0.03],
    [0.6, 0.67, -0.03], [0.72, 0.6], [0.72, 0.46], [0.72, 0.56, -0.03],
    [0.72, 0.67, -0.03],
  ]),
  // Verified against classifySign() — see the file header.
  V: pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.43, 0.7], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.53, 0.6], [0.53, 0.46], [0.53, 0.32],
    [0.53, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.56, -0.03],
    [0.6, 0.67, -0.03], [0.72, 0.6], [0.72, 0.46], [0.72, 0.56, -0.03],
    [0.72, 0.67, -0.03],
  ]),
  // Verified against classifySign() — see the file header.
  W: pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.37, 0.66],
    [0.43, 0.7], [0.36, 0.6], [0.36, 0.46], [0.36, 0.32],
    [0.36, 0.18], [0.48, 0.6], [0.48, 0.46], [0.48, 0.32],
    [0.48, 0.18], [0.6, 0.6], [0.6, 0.46], [0.6, 0.32],
    [0.6, 0.18], [0.72, 0.6], [0.72, 0.46], [0.72, 0.56, -0.03],
    [0.72, 0.67, -0.03],
  ]),
  // Verified against classifySign() — see the file header.
  Y: pose([
    [0.5, 0.9], [0.36, 0.79], [0.29, 0.71], [0.17, 0.67],
    [0.05, 0.63], [0.36, 0.6], [0.36, 0.46], [0.36, 0.56, -0.03],
    [0.36, 0.67, -0.03], [0.48, 0.6], [0.48, 0.46], [0.48, 0.56, -0.03],
    [0.48, 0.67, -0.03], [0.6, 0.6], [0.6, 0.46], [0.6, 0.56, -0.03],
    [0.6, 0.67, -0.03], [0.72, 0.6], [0.72, 0.46], [0.72, 0.32],
    [0.72, 0.18],
  ]),
};

export const HAND_CONNECTIONS: [number, number][] = [
  [0, 1], [1, 2], [2, 3], [3, 4], // thumb
  [0, 5], [5, 6], [6, 7], [7, 8], // index
  [9, 10], [10, 11], [11, 12], // middle
  [13, 14], [14, 15], [15, 16], // ring
  [0, 17], [17, 18], [18, 19], [19, 20], // pinky
  [5, 9], [9, 13], [13, 17], // palm
];
