import { Link } from 'react-router-dom';
import type { RoundResult, UserProfile } from '../lib/contracts';

export function RoundComplete({ result, profile, onRetry }: { result: RoundResult; profile: UserProfile; onRetry: () => void }) {
  return <section className="mx-auto max-w-xl overflow-hidden rounded-2xl border border-line bg-surface text-center" aria-labelledby="round-title">
    <div className="bg-soft px-6 pt-10 pb-8"><div aria-hidden="true" className="mx-auto flex h-20 w-20 items-center justify-center rounded-2xl border-2 border-brand bg-soft text-4xl text-brand">✓</div><p className="mt-6 text-xs font-bold tracking-widest text-brand uppercase">Practice complete</p><h2 id="round-title" className="mt-3 text-3xl font-extrabold">Look what your hands can do.</h2><p className="mt-3 text-sm text-muted">{result.correct > 0 ? 'You made progress. Keep that momentum going.' : 'Every attempt is practice. Try again at your own pace.'}</p></div>
    <div className="p-6 sm:p-8"><div className="grid grid-cols-3 gap-3">{[['XP earned', `+${result.xp}`], ['Confirmed', `${result.correct}`], ['Score', `${result.score}`]].map(([label, value]) => <div key={label} className="rounded-2xl border border-line py-4"><p className="text-xs text-muted">{label}</p><p className="mt-2 text-2xl font-bold text-brand">{value}</p></div>)}</div><p className="mt-5 text-sm text-muted">Level {profile.level} · {profile.xp} total XP · {profile.streak} day streak</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button onClick={onRetry} className="flex-1 rounded-xl border border-brand bg-brand text-white px-5 py-3 font-bold hover:bg-brand-hover">Practice again</button><Link to="/leaderboard" className="flex-1 rounded-xl border border-line bg-soft px-5 py-3 font-bold hover:bg-line">View leaderboard</Link></div><Link to="/" className="mt-5 inline-block text-sm text-muted underline underline-offset-4">Back to your journey</Link></div>
  </section>;
}
